global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3001']

  - job_name: 'microservice-1'
    static_configs:
      - targets: ['microservice-1:5672']

  - job_name: 'microservice-2'
    static_configs:
      - targets: ['microservice-2:6379']