apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  labels:
    app: api-gateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/path: /metrics
        prometheus.io/port: '3001'
    spec:
      containers:
      - name: api-gateway
        image: your-docker-username/api-gateway:latest
        ports:
        - containerPort: 3001
        env:
        - name: NODE_ENV
          value: "development"
        - name: RMQ_URL
          value: "amqp://rabbitmq:5672"
        - name: RMQ_QUEUE
          value: "microservice_1_queue"
        - name: MICROSERVICE_1_RMQ_QUEUE
          value: "microservice_1_queue"
        - name: REDIS_HOST
          value: "redis"
        - name: REDIS_PORT
          value: "6379"
        - name: MICROSERVICE_1_REDIS_DB
          value: "1"
        - name: MICROSERVICE_2_REDIS_DB
          value: "2"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_PORT
          value: "5432"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: postgres-password
        - name: LOG_LEVEL
          value: "info"