apiVersion: v1
kind: Service
metadata:
  name: nestjs-microservices
  labels:
    app: nestjs-microservices
spec:
  ports:
    - port: 80
      targetPort: 3001  # Adjust to match your containerPort if different
  selector:
    app: nestjs-microservices
