scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s

    static_configs:
      - targets: ['localhost:3001']
        labels:
          service: 'app-exporter'
          group: 'testing'
          name: 'app-exporter'
